<?php
namespace backend\controllers;



use Yii;

use common\models\guanli_quanxian\AdminUser;
use common\models\guanli_quanxian\BackendUser;
use common\models\guanli_quanxian\AdminUserRole;
use common\utils\CommonFun;
/**
 * Site controller
 */
class SiteController extends BaseController
{
    public function beforeAction($action)
    {

        if(Yii::$app->user->isGuest){
            $this->layout='lte_main_login';
          return $this->render('login',[Yii::$app->request->csrfParam=>Yii::$app->request->getCsrfToken()]);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 文件缓存
     * @return array
     */
    public function behaviors()
    {
        $behaviors[]=  [
            'class' => 'yii\filters\PageCache', // 设置需要加载的缓存文件
            'only' => ['index'], // 设置需要缓存的控制器
            'duration' => 1000, // 设置过期时间
            'dependency' => [ // 设置依赖关系
                'class' => 'yii\caching\FileDependency',
                'fileName' => 'robots.txt'
            ]
        ];
        return $behaviors;
    }
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
       if(Yii::$app->user->isGuest){
            return $this->render('login',[Yii::$app->request->csrfParam=>Yii::$app->request->getCsrfToken()]);
        }
        else{


            $sysInfo = [
                ['name'=> '操作系统', 'value'=>php_uname('s')],  //'value'=>php_uname('s').' '.php_uname('r').' '.php_uname('v')],
                ['name'=>'PHP版本', 'value'=>phpversion()],
                ['name'=>'程序版本', 'value'=>Yii::getVersion()],
                ['name'=>'数据库', 'value'=>$this->getDbVersion()],
                ['name'=>'模版版本', 'value'=>'V2.3.6'],
                ['name'=>'建议和BUG', 'value'=>\Yii::$app->request->hostInfo.'/bbs'],
            ];
            return $this->render('index', [
                'sysInfo'=>$sysInfo
            ]);
        }
    }
    /**
     * Logs in a user.
     * @return mixed
     */
/*    public function actionLogin()
    {

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $username = Yii::$app->request->post('username');
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            AdminUser::updateAll(
                ['last_ip' => CommonFun::getClientIp()],
                ['uname' => $username],
                ['is_online' => 'y']

            );
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }*/

    public static function actionLogin()
    {
        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $rememberMe = Yii::$app->request->post('remember');
        $rememberMe = $rememberMe == 'y' ? true : false;
        if(AdminUser::login($username, $password, $rememberMe) == true){
           $user= AdminUser::findOne(['uname' => $username]);
           $user->last_ip=CommonFun::getClientIp();
           $user->is_online='y';
           $ret=$user->validate()?$user->save():$user->getErrors();
     //       return $this->goHome();
              return json_encode(['errno'=>$ret?0:-1]);
        } else{
            return json_encode(['errno'=>2]);
        }

    }
    //restful登录版
    public function actionLoginOauth()
    {

        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $rememberMe = Yii::$app->request->post('remember');
        $rememberMe = $rememberMe == 'y' ? true : false;
        if(AdminUser::login($username, $password, $rememberMe) == true){
            $user= AdminUser::findOne(['uname' => $username]);
            $user->last_ip=CommonFun::getClientIp();
            $user->is_online='y';
            $ret=$user->validate()?$user->save():$user->getErrors();
            return json_encode(['errno'=>$ret?Header("Location: ".Yii::getAlias('@apisite').'v1/a-list/t&id=1'):-1]);

        } else{
            return json_encode(['errno'=>2]);
        }

    }

    public function actionTest(){
       // \Yii::$app->viewPath='@app/views/mobile';
        return $this->render('test');
    }
    public function actionLogout()
    {
        $this->layout='lte_main_login';
        Yii::$app->user->isGuest?false:AdminUser::updateAll( ['is_online' => 'n'], ['id' =>Yii::$app->user->identity->getId()]);
        Yii::$app->user->logout();
        return $this->goHome();
    }
    public function actionPsw()
    {
       $userRole = AdminUserRole::find()->with('role')->andWhere(['user_id'=>Yii::$app->user->identity->id])->one();
        return $this->render('psw',[
            'user_role' => $userRole->role->name
        ]);
    }
    public function actionPswSave()
    {
        $old_password = Yii::$app->request->post('old_password', '');
        $new_password = Yii::$app->request->post('new_password', '');
        $confirm_password = Yii::$app->request->post('confirm_password', '');
        if(empty($old_password) == true){
            $msg = array('error'=>2, 'data'=>array('old_password'=>'旧密码不正确'));
            echo json_encode($msg);
            exit();
        }
        if(empty($new_password) == true){
            $msg = array('error'=>2, 'data'=>array('new_password'=>'新密码不能为空'));
            echo json_encode($msg);
            exit();
        }
        if(empty($confirm_password) == true){
            $msg = array('error'=>2, 'data'=>array('confirm_password'=>'确认密码不能为空'));
            echo json_encode($msg);
            exit();
        }
        if($new_password != $confirm_password){
            $msg = array('error'=>2, 'data'=>array('confirm_password'=>'两次新密码不相同'));
            echo json_encode($msg);
            exit();
        }
        if(Yii::$app->user->isGuest == false){
            $user = AdminUser::findByUsername(Yii::$app->user->identity->uname);
            if(BackendUser::validatePassword($user, $old_password) == true){
                $user->password = Yii::$app->security->generatePasswordHash($new_password);
                $user->save();
                $msg = array('errno'=>0, 'msg'=>'保存成功');
                echo json_encode($msg);
            }
            else{
                $msg = array('errno'=>2, 'data'=>array('old_password'=>'旧密码不正确'));
                echo json_encode($msg);
            }
        }
        else{
            $msg = array('errno'=>2, 'msg'=>'请先登录');
            echo json_encode($msg);
        }
    }
    private function getDbVersion(){
        $driverName = Yii::$app->db->driverName;
        if(strpos($driverName, 'mysql') !== false){
            $v = Yii::$app->db->createCommand('SELECT VERSION() AS v')->queryOne();
            $driverName = $driverName .'_' . $v['v'];
        }
        return $driverName;
    }
}
