<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/18
 * Time: 4:44
 */

namespace frontend\controllers;


use yii\web\Controller;

class BaseController extends Controller
{
    public $layout = "ec";

    public function beforeAction($action)
    {
        header('Access-Control-Allow-Origin:'.\Yii::$app->params[ 'clientDomain']);
      // $this->enableCsrfValidation=false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}