<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/30
 * Time: 10:17
 */

namespace common\components\common;


use yii\base\Widget;

class EcAjaxFormWidget extends Widget
{
    public $action;
    public $formId;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('ec-ajax-form',['action'=>$this->action,'formId'=>$this->formId]);
    }
}