<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/1
 * Time: 2:49
 */

namespace common\components\common;


use yii\base\Widget;
use \yii\caching\TagDependency;

/**
 * Yii片段缓存
 * @package common\components\common
 */
class YiiPdhcWidget extends Widget
{

    public $cacheId;
    public $options=[];
    public $content;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('yii-pianduan-huancun',[
            'cacheId'=>$this->cacheId,
            'options'=>$this->options,
            'content'=>$this->content
        ]);
    }

    public static function t(){
        TagDependency::invalidate(\Yii::$app->cache, 'key');
    }

    public static function getDbDependency($sql='SELECT MAX(updated_at) FROM post'){
     return   $dependency = [
            'class' => 'yii\caching\DbDependency',
            'sql' =>$sql ,
        ];
    }

    public static function getTagDependency($tags='key'){
        $dependency = [
            'class' => 'yii\caching\TagDependency',
            'tags' =>$tags ,                  //此处为自定义方法：获取生成的tag
        ];
    }

    public static function getTimeDependency($duration=3600){
        return ['duration' => $duration];
    }
}