<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/25
 * Time: 8:19
 */

namespace common\components\ec\frontend\gouwuche\tijiaodingdan;


use yii\base\Widget;

class EcFeiyongZongjiWidget extends Widget
{

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('ec-feiyong-zongji',[]);
    }
}