<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/25
 * Time: 8:09
 */

namespace common\components\ec\frontend\gouwuche\tijiaodingdan;


use yii\base\Widget;

class EcPeisongFangshiWidget extends Widget
{
    public $kuaidi_model;
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('ec-peisong-fangshi',['kuaidi_model'=>$this->kuaidi_model]);
    }
}