<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/24
 * Time: 21:12
 */

namespace common\components\eleme;


use yii\base\Widget;

class ElButtonWidget extends Widget
{

    public $buttonText='弹窗按钮';
    public $btnClass='info';
    //正在加载
    public $loading='false';
    //按钮大小
    public $size='large';
    //是否禁用
    public $disabled='false';
    public $plain='false';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('el-button',[
            'disabled'=>$this->disabled,
             'buttonText'=> $this->buttonText,
            'btnClass'=> $this->btnClass,
            'size'=>$this->size,
            'loading'=>$this->loading,
            'plain'=>$this->plain,
        ]);
    }
}