<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/21
 * Time: 10:25
 */

namespace common\components\eleme;



use yii\base\Widget;

class LeftMenuWidget extends Widget
{
    public $headerTitle='';

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
      //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('el-left-menu');
    }



}