<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/21
 * Time: 15:05
 */

namespace common\components\eleme;


use Yii;
use yii\base\Widget;

class ElTanchuangDialogWidget extends Widget
{
    public $dialogTitle='对话框标题';
    public $buttonText='弹窗按钮';
    public $btnClass='primary';
    public $html='html内容';
    public function init()
    {
         parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('el-tanchuang-dialog',[
            'dialogTitle'=> $this->dialogTitle,
            'buttonText'=> $this->buttonText,
            'btnClass'=> $this->btnClass,
            'html'=>$this->html,
        ]);
    }
}