<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/22
 * Time: 0:50
 */

namespace common\components\eleme;


use yii\base\Widget;

class ElTreeCheckboxWidget extends Widget
{
    public $label='label';
    public $children='children';
    public $treeCheckBox='';
    public function init()
    {
        is_array($this->treeCheckBox)?$this->treeCheckBox=json_encode($this->treeCheckBox):'';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('el-tree-checkbox');
    }
}