<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 20:11
 */

namespace common\components\ec\backend;


use Yii;
use yii\base\Widget;

class EcBackendFooterWidget extends Widget
{
    public $url='all';
    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('ec-backend-footer',['url'=>$this->url]);
    }
}