<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 21:38
 */

namespace common\components\ec\backend;


use yii\base\Widget;

class EcLteDelDialogWidget extends Widget
{
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-lte-del-dialog');
    }
}