<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/31
 * Time: 16:24
 */

namespace common\components\ec\backend;


use yii\base\Widget;

class EcTianjiaXinshangpinWidget extends Widget
{
    public $model;

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('shangpin-guanli/ec-tianjia-xinshangpin',['model'=>$this->model]);
    }
}