<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/2
 * Time: 3:52
 */

namespace common\components\easyui;


use yii\base\Widget;

class EuiCrudWidget extends Widget
{
    public $action;
    public $formId;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('ec-ajax-form',['action'=>$this->action,'formId'=>$this->formId]);
    }
}