<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/2
 * Time: 3:53
 */

namespace common\components\easyui;


use yii\base\Widget;

class EuiCdnWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('eui-cdn',[]);
    }
}