<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/24
 * Time: 12:26
 */

namespace common\components\bootstrap;


use yii\base\Widget;

class BpButtonWidget extends Widget
{
    public $text='按钮';
    public $class='btn btn-primary';
    public function init()
    {
         parent::init(); // TODO: Change the autogenerated stub
    }

    //默认按钮
    public function setBaiSe(){
        $this->class='btn btn-default';
    }

        //原始按钮
    public function setLanSe(){
        $this->class='btn btn-primary';
    }

    //成功按钮
    public function setLvSe(){
        $this->class='btn btn-success';
    }
        //信息按钮
    public function setDanLanSe(){
        $this->class='btn btn-info';
    }
    //警告按钮
    public function setChengSe(){
        $this->class='btn btn-warning';
    }
    //危险按钮
    public function setHongSe(){
        $this->class='btn btn-danger';
    }
    //链接按钮
    public function setLinJie(){
        $this->class='btn btn-link';
    }
    //==========================================按钮大小========================================================
    //大的原始按钮
    public function setDaBai(){
        $this->class='btn btn-primary btn-lg';
    }
    //小的原始按钮
    public function setXiaoLan(){
        $this->class='btn btn-primary btn-sm';
    }
    //小的按钮
    public function setXiaoBai(){
        $this->class='btn btn-default btn-sm';
    }
    //特别小的原始按钮
    public function setTeXiaoLan(){
        $this->class='btn btn-primary btn-xs';
    }
    //特别小的按钮
    public function setTeXiaoBai(){
        $this->class='btn btn-default btn-xs';
    }

    //块级的原始按钮
    public function setKuaiJiLan(){
        $this->class='btn btn-primary btn-lg btn-block';
    }
    //块级的按钮
    public function setKuaiJiBai(){
        $this->class='btn btn-default btn-lg btn-block';
    }

    //========================================================大小结束========================================================

    ///=========================按钮状态===================================
    public function setJiHuoBaiDa(){
        $this->class='btn btn-default btn-lg active';
    }
    public function setJiHuoLanDa(){
        $this->class='btn btn-primary btn-lg active';
    }
    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return '<button type="button" class="'.$this->class.'">'.$this->text.'</button>';
    }
}