<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/26
 * Time: 15:30
 */

namespace common\components\vue;


use yii\base\Widget;

class VGuoDuTtranslateWidget extends Widget
{
    public $dialogTitle = '对话框标题';
    public $buttonText = '弹窗按钮';
    public $btnClass = 'primary';
    public $html = 'html内容';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('v-guodu-translate', []);
    }
}