<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/4
 * Time: 14:02
 */

namespace common\components\vue;


use yii\base\Widget;

class VHttpVueResourceWidget extends Widget
{
    public $buttonText='按钮文本';
    public $msg='提示的消息';
    public $btnClass="primary";
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        return $this->render('v-http-vue-resource',['buttonText'=>$this->buttonText,'msg'=>$this->msg, 'btnClass' => $this->btnClass]);
    }
}