<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/26
 * Time: 15:54
 */

namespace common\components\vue;


use yii\base\Widget;

class VPropsWidget extends Widget
{
    public $buttonText='按钮文本';
    public $msg='提示的消息';
    public $btnClass="primary";
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        return $this->render('v-props',['buttonText'=>$this->buttonText,'msg'=>$this->msg, 'btnClass' => $this->btnClass]);
    }
}