<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/4
 * Time: 13:48
 */

namespace common\components\vue;


use yii\base\Widget;

class VSlotsWidget extends Widget
{

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        return $this->render('v-slots',[]);
    }
}