<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/31
 * Time: 2:34
 */

namespace common\components\vue;


use yii\base\Widget;

class VTabsSwitchWidget extends Widget
{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('v-tabs-switch', []);
    }
}