<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/13
 * Time: 14:00
 */

namespace common\components\vue;


use yii\base\Widget;

class VueBaiduMapWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('vue-baidu-map', []);
    }
}