<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/12
 * Time: 16:17
 */

namespace common\components\vue;


use yii\base\Exception;
use yii\base\Widget;

class VueExtendWidget extends Widget
{
    public $ctorId=null;
    /**
     * 布局文件选择器
     * @var
     */
    public $mount;

    /**
     * 比如
     * @var data methods created组合成的json对象
     */
    public $extend;
    public function init()
    {
      parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if($this->ctorId==null){
          return  json_encode(['请设置Ctor的id',-1,null],JSON_UNESCAPED_UNICODE);
        }
        return $this->render('vue-extend', ['mount'=>$this->mount,'extend'=>$this->extend,'ctorId'=>$this->ctorId]);
    }
}