<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 10:03
 */

namespace common\components\ec\frontend;


use common\models\guanli_wenzhang\ArticleCatModel;
use common\models\guanli_wenzhang\ArticleModel;
use Yii;
use yii\base\Widget;

class EcFooterWidget extends Widget
{
    public $url='all';
    public $aboutItems;
    public $helps;
    public function init()
    {
        //帮助文章
       $this->helps=json_encode(ArticleCatModel::find()->where(['cat_type'=>5])->joinWith(['articleModel'])->asArray()->all());
       //底部联系我们那些
        $this->aboutItems=json_encode(ArticleModel::find()->where(['cat_id'=>2])->select(['title','article_id',])->asArray()->all());
        $this->url=Yii::getAlias($this->url);
        parent::init();
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-footer',['url'=>$this->url,'aboutItems'=>$this->aboutItems,'helps'=>$this->helps]);
    }
}