<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/3
 * Time: 23:21
 */

namespace common\components\ec\frontend;


use Yii;
use yii\base\Widget;

class EcGouwucheShangpinWidget extends Widget
{
    public $url='all';
    public $cartModel;
    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-gouwuche-shangpin',['url'=>$this->url,'cartModel'=>$this->cartModel]);
    }
}