<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/3
 * Time: 17:53
 */

namespace common\components\ec\frontend;


use Yii;
use yii\base\Widget;

class EcGoumaiJiluWidget extends Widget
{
    public $url='all';
    public $model;
    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-goumai-jilu',['url'=>$this->url,'model'=>$this->model]);
    }
}