<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 10:13
 */

namespace common\components\ec\frontend;


use common\models\guanli_shangpin\GoodsModel;
use Yii;
use yii\base\Widget;

class EcJingpinTuijianWidget extends Widget
{
    public $url='all';
    public $items;
    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        $this->items=json_encode(GoodsModel::find()->select(['goods_id','goods_name','goods_thumb','goods_name','shop_price'])
            ->where(['is_best'=>1])->asArray()->all());
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-jingpin-tuijian',['url'=>$this->url,'items'=>$this->items]);
    }
}