<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 13:39
 */

namespace common\components\ec\frontend;


use yii\base\Widget;

class EcMenuDlWidget extends Widget
{

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return '  <dl>
                <dt><a href="http://ec.com/category.php?id=1">手机类型</a></dt>
                <dd><a href="http://ec.com/category.php?id=2">CDMA手机</a></dd>
                <dd><a href="http://ec.com/category.php?id=3">GSM手机</a></dd>
                <dd><a href="http://ec.com/category.php?id=4">3G手机</a></dd>
                <dd><a href="http://ec.com/category.php?id=5">双模手机</a></dd>
            </dl>';
    }
}