<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 10:15
 */

namespace common\components\ec\frontend;


use common\models\guanli_shangpin\BrandModel;
use Yii;
use yii\base\Widget;

class EcPinPaiWidget extends Widget
{
    public $url='all';
    public $items;
    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        $this->items=json_encode(BrandModel::find()->select(['brand_id','brand_name','brand_logo'])->where(['not',['brand_logo'=>'']])->asArray()->all());
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-pinpai',['url'=>$this->url,'items'=>$this->items]);
    }
}