<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 10:16
 */

namespace common\components\ec\frontend;


use common\models\guanli_shangpin\GoodsModel;
use Yii;
use yii\base\Widget;

class EcReMaiWidget extends Widget
{
    public $url='all';
    public $items;
    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        $this->items=json_encode(GoodsModel::find()->select(['goods_id','shop_price','goods_name','goods_thumb'])->where(['is_hot'=>1])->limit(15)
            ->asArray()->all());
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-remai',['url'=>$this->url,'items'=>$this->items]);
    }
}