<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 10:06
 */

namespace common\components\ec\frontend;


use common\components\common\YiiSuanfaWidget;

use common\models\guanli_shangpin\CategoryModel;
use common\utils\CommonFun;
use Yii;
use yii\base\Widget;

class EcSearchWidget extends Widget
{
    public $url='all';
    public $trees;
    public function init()
    {
        $items=CategoryModel::find()->asArray()->all();
      $this->trees= json_encode(YiiSuanfaWidget::getTree($items));
        $this->url=Yii::getAlias($this->url);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //  parent::run(); // TODO: Change the autogenerated stub
        return $this->render('ec-search',['trees'=>$this->trees]);
    }
}