<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/5
 * Time: 13:55
 */

namespace common\components\ec\frontend;


use Yii;
use yii\base\Widget;

class EcShangpinTupianHualangWidget extends Widget
{
    public $url='all';

    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
         return $this->render('ec-shangpin-tupian-hualang',['url'=>$this->url]);
    }
}