<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/2
 * Time: 11:12
 */

namespace common\components\ec\frontend;


use Yii;
use yii\base\Widget;

class EcShangpinXinxiWidget extends Widget
{
    public $url='all';
    public $model;
    public $rank_model;
    public $guige_model;

    public function init()
    {
        $this->url=Yii::getAlias($this->url);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {


        return $this->render('ec-shangpin-xinxi',['url'=>$this->url,'rank_model'=>$this->rank_model,'items'=>json_encode($this->model),'guige_model'=>json_encode($this->guige_model,JSON_UNESCAPED_UNICODE)]);
    }
}