<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/1
 * Time: 10:34
 */

namespace common\components\ec\frontend;


use Yii;
use yii\base\Widget;

class EcYonghuDengluWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('ec-yonghu-denglu');
    }
}